### ISSUE TITLE
Recovery.img从发布中丢失

### ISSUE THREAD

**Issue by curtisy1** [youyim123/android_device_nubia_nx606j#2]
嗨youyim，

你发布了一个链接到[recovery.img](https://github.com/youyim123/android_device_nubia_nx606j/releases/download/test/recovery.img)的版本，但zip中缺少该文件。 这只是我们不能使用的已经发布的那个。 如果您决定公开，请分享，这样我就可以恢复我的手机存储至少因为它在引导循环中停留。

谢谢你，对不起中国人。 我不得不用Google翻译

**Comment by youyim123** [comment]
> 嗨youyim，
> 
> 你发布了一个链接到[recovery.img](https://github.com/youyim123/android_device_nubia_nx606j/releases/download/test/recovery.img)的版本，但zip中缺少该文件。 这只是我们不能使用的已经发布的那个。 如果您决定公开，请分享，这样我就可以恢复我的手机存储至少因为它在引导循环中停留。
> 
> 谢谢你，对不起中国人。 我不得不用Google翻译

https://github.com/youyim123/android_device_nubia_nx606j/releases/download/test/recovery.img

**Comment by youyim123** [comment]
@curtisy1 
ifeq ($(BOARD_AVB_ENABLE), true)
   BOARD_AVB_RECOVERY_KEY_PATH := external/avb/test/data/testkey_rsa4096.pem
   BOARD_AVB_RECOVERY_ALGORITHM := SHA256_RSA4096
   BOARD_AVB_RECOVERY_ROLLBACK_INDEX := 1
   BOARD_AVB_RECOVERY_ROLLBACK_INDEX_LOCATION := 1
endif
